To Extract Features from SIFT

Make sure to copy the train-features folder to <../data/train-features>

```{r}
features_all = list()
keypoints_all = list()

sift_feature_dir <- "../data/train-features/" # This will be modified for different data sets.

for (i in 1:2000){
  file = sprintf("pet%i.jpg.sift.RData", i)
  file_path = paste0(sift_feature_dir,file)
  load(file_path)
  features_all[[i]] = features
  keypoints_all[[i]] = keypoints
}

<<<<<<< HEAD
features_all = do.call("rbind",features_all)
```

Now there should be a features_all, and keypoints_all, both length 2000 lists. pet1.jpg.sift corrosponds to features_all[1], etc.

```{r}
#Kmeans stuff

km.out = kmeans(features_all, 1000, iter.max = 30000, algorithm = "Lloyd")
save(km.out, file = '100kmeans.rda')
```

```{r}
#Loading a pretrained kmeans
#SIFT features in same place as before

load('100kmeans.rda')

closest.cluster <- function(x) {
  cluster.dist <- apply(k.out$centers, 1, function(y) sqrt(sum((x-y)^2)))
  return(which.min(cluster.dist)[1])
}

sift_feature_dir <- "../data/train-features/" # This will be modified for different data sets.

data = list()

for (i in 1:2000){
  print(i)
  file = sprintf("pet%i.jpg.sift.RData", i)
  file_path = paste0(sift_feature_dir,file)
  load(file_path)
  feature_clusters <- get.knnx(k.out$centers, features, 1)$nn.index[,1]
  feature_vec <- rep(0,100)
  for (j in 1:length(feature_clusters)){
  c = feature_clusters[j]
  feature_vec[c] = feature_vec[c]+ 1}
  data[[i]] = feature_vec
}

data = do.call("rbind", data)
=======
d <- data.frame()
for (i in 1:2000){
  d <- rbind(d, c(features_all[[i]]))
}
# Attempting to make into a matrix below
# df <- do.call("rbind",features_all)
# max.len <- max(sapply(features_all, length))
# features_all_list <- lapply(features_all, function(x) {c(x, rep(NA, max.len - length(x)))})
# features_all_matrix <- do.call(rbind, features_all_list)
#write.csv(features_all, "../output/SIFT_features.csv")
>>>>>>> 8c06288670fdecf40d5d21c7d656a60a365810a7

```

So now there's a "data"" variable with 2000 rows, 100 columns

